### ISSUE TITLE
Organograma (aberto a mudanças)

### ISSUE THREAD

**Issue by gab0gomes** [devsertao/quem-somos#2]
## [Organograma (clique para ver)](https://www.figma.com/file/VNggGpXp5Ys3Xr8zr8ieCM/Organiza%C3%A7%C3%A3o?node-id=1%3A2)

A ideia é que a comunidade gire em torno de guildas.

Uma guilda é um subconjunto de pessoas unidas por um interesse específico, por exemplo:

* UX
* Testes automatizados
* Front-end
* Back-end
* Mulheres
* Diversidade
* Agilidade
* etc...

Cada guilda terá um líder, o papel do líder é unificar as vozes e gerenciar os eventos, ações, etc, daquela guilda.

O líder de guilda não é hierarquicamente superior a ninguém da guilda.

Além da guilda, teremos o gerente geral, gerente de marca, gerente de comunidade e gerente de eventos, essas pessoas serão responsáveis pela imagem, cronograma, comunicação, parcerias e patrocínios do DevSertão em um âmbito mais geral.

Assim como o líder de guilda, nenhum manager é hierarquicamente superior a ninguém da comunidade.

A comunicação entre todos do DevSertão deve ser aberta independentemente do papel desempenhado por cada pessoa.

**Comment by esron** [comment]
Como vai funcionar a nomeação dos papeis? Eleições?

Quanto tempo a pessoa passa ocupando o papel?

**Comment by gab0gomes** [comment]
> Como vai funcionar a nomeação dos papeis? Eleições?
> 
> Quanto tempo a pessoa passa ocupando o papel?

A princípio por voluntariado e afinidade.

O tempo que ela quiser, tiver desempenhando um bom papel e a comunidade estiver de acordo.

**Comment by gab0gomes** [comment]
Como queremos que não haja hierarquia dentro do coletivo, o organograma foi atualizado. As guildas temáticas continuam existindo, os antigos gerentes se tornaram membros da guilda core, e em vez de gerentes, agora são líderes assim como o guild leader.

**Comment by esron** [comment]
Tem como resumir o que cada papel deve fazer? Ou ainda está aberto também?

**Comment by gab0gomes** [comment]
### Core Guild - Responsável pelo posicionamento geral do coletivo
* Brand Lead - Responsável pelas artes divulgação, logo, linguagem e etc. Comunicação.
* Community Lead - Responsável pelas redes sociais, ouvir feedback, coletar anseios da comunidade e etc.
* Event Lead - Responsável por gerencias os eventos de forma mais global, calendário, plataforma e etc.
* Orchestrator - Garante que essas pessoas se comuniquem, é um(a) facilitador(a).

### Themed Guild - Responsável por promover os eventos, conteúdos, mentorias e etc daquele tema
* Guild Lead - Responsável pela comunicação das vontades da guilda, facilita a interação.
* Member - Voluntário da guilda. Modera chat, participa das discussões, ajuda na divulgação, palestra e etc.

### External - Participantes externos
* Partner - CPF ou CNPJ parceiro de um evento específico ou de uma guilda específica
* Sponsor - CPF ou CNPJ que ajuda financeiramente na realização de um evento ou na manutenção de uma guilda.
* Guest - Convidado(a) participante de uma das ações da guilda, mas que não é um membro.

**Comment by clebsf** [comment]
Achei muito show essa iniciativa do DevSertão. Se possível, gostaria de contribuir também. Fico a disposição. ;)

**Comment by gab0gomes** [comment]
Eu coloquei as responsabilidades dos papeis, mas elas não são exclusivas. É apenas pra gente ter alguém responsável por isso, mas todo mundo do coletivo pode ajudar em tudo.

**Comment by victorgso001** [comment]
Acho que dá pra ter uma guilda de pesquisa tb não?

**Comment by gab0gomes** [comment]
> Acho que dá pra ter uma guilda de pesquisa tb não?

Seria uma themed guild

**Comment by victorgso001** [comment]
Ah, show

**Comment by victorgso001** [comment]
Pra mim, desse jeito tá massa. Depois de fechar é definir os papéis né?

**Comment by gab0gomes** [comment]
Não sei se deixei claro, não tem uma quantidade de guildas específicas. Um guilda existe se existem pessoas querendo falar sobre aquele assunto e existe alguém para ser o guild leader.

**Comment by gab0gomes** [comment]
> Pra mim, desse jeito tá massa. Depois de fechar é definir os papéis né?

Os papéis estão definidos acima. Leader, member, partner, etc...

**Comment by gab0gomes** [comment]
Acredito que podemos seguir assim, caso haja necessidade, faremos alterações no futuro.

**Comment by gab0gomes** [comment]
> Achei muito show essa iniciativa do DevSertão. Se possível, gostaria de contribuir também. Fico a disposição. ;)

[OFF]

@clebertsfigueiredo dá uma olhada nas [guildas](https://github.com/devsertao/quem-somos#guildas) talvez tu se interesse por alguma ou queira sugerir outra que ainda não tá lá (abre uma issue nesse repositório).
