### ISSUE TITLE
[Reunião Geral] - 16/06/2021

### ISSUE THREAD

**Issue by jamesdasilva** [devsertao/quem-somos#4]
Pauta:

1 - Composição do coletivo
3 - Objetivos
2 - Agenda

**Comment by esron** [comment]
Pode contar comigo.

**Comment by esron** [comment]
Vamos ver uma data, acredito que seja mais fácil ou a noite ou em um final de semana pra ter mais gente.

**Comment by larisrocks** [comment]
reunião de alinhamento devsertao - notas
16/06/21
inicio: 20:10	termino:21:15

pauta:
**- reorganização/organograma**

discussão:
	revisão de gargalos para funcionamento;
	refazer system design;
	reestruturar o coletivo por principios básicos de secretarias ou comissões 
		Organização: gerencia e manutenção interna do coletivo 
		Política: manter coerencia de ações do coletivo no que se refere a missão, valores, propósito
		Finanças: gestão de recursos, possíveis parceirias, patrocínios.
encaminhamento:
	Gabriel, Larissa, Talita e Esron ficam responsáveis por revisar e propor documento sobre essa nova organização na próxima reunião interna, marcada para 7 de julho.

**- objetivos**

discussão:
	esclarecimento sobre a proposta das guildas e avaliação do não funcionamento;
	sugestão: grupos de estudo e mais atividades internas para fomentar de fato a comunidade DevSertão;
	proposta de evento: devSertao Convida, para expor palestras de fora do Vale do São Francisco. Possibilidade de conexão com outros coletivos.

encaminhamento:
	após reorganização geral, na divisão de tarefas pelo devSertaoCore, os pontos discutidos serão estruturados e consolidados.

**- agenda**
discussão:
	buscar inspiração em diversos eventos;
	fazer reuniões internas mensalmente;
	intercalar eventos de forma também mensal.

encaminhamento:
	Open Space 2 - 19/junho
	Pocket event Recepção de Calouros - previsão 10 de julho (responsáveis: Talita e Larissa)
	Reunião interna - 7 de julho
	Proximo DevSertão - estimativa agosto
